# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
encoding: UTF-8
title:            Dustin White
tagline:          'Department of Economics, UNO'
description:      'Department of Economics, UNO'
url:              https://dustywhite7.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Dustin White'
  url:            https://twitter.com/dustywhite7

paginate:         10

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/dustywhite7/dustywhite7.github.io
